packages:
  - "."
  - "../owl-ui"
  - "../owl-admin-ui"
  - "../owl-cms/fronted/admin"
  - "../owl-workorder/fronted/admin"
  - "../lift-vision/fronted/admin"
  - "../owl-portal/fronted/admin"
  - "../asset-manage/fronted/admin"

