/**
 * 用法：pnpm dev <project> / pnpm build <project>
 * 例如：pnpm dev asset
 */
import { spawnSync } from "node:child_process";
import {
  existsSync,
  readFileSync,
  rmSync,
  writeFileSync
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const mode = process.argv[2];
const project = process.argv[3];

function fail(msg) {
  console.error(msg);
  process.exit(1);
}

if (mode !== "dev" && mode !== "build") {
  fail(
    `用法: node scripts/run-project.mjs <dev|build> <project>\n示例: pnpm dev asset`
  );
}

if (!project || project.startsWith("-")) {
  const yamlPath = join(root, "builder.projects.yaml");
  let hint = "";
  if (existsSync(yamlPath)) {
    const raw = readFileSync(yamlPath, "utf8");
    const map = parseYaml(raw);
    if (map && typeof map === "object") {
      hint = `\n已在 builder.projects.yaml 登记的项目：${Object.keys(map).join(", ")}`;
    }
  }
  fail(`请指定项目名，例如：pnpm ${mode} asset${hint}`);
}

const yamlPath = join(root, "builder.projects.yaml");
if (!existsSync(yamlPath)) {
  fail(`缺少配置文件：${yamlPath}`);
}

const projectsMap = parseYaml(readFileSync(yamlPath, "utf8"));
if (!projectsMap || typeof projectsMap !== "object") {
  fail(`${yamlPath} 格式错误：应为「项目名: 标题」的映射`);
}

const title = projectsMap[project];
if (typeof title !== "string" || !title.trim()) {
  fail(
    `项目 "${project}" 未在 builder.projects.yaml 中配置标题。\n可选项目：${Object.keys(projectsMap).join(", ")}`
  );
}

const entryFile = join(root, "src", `${project}.ts`);
if (!existsSync(entryFile)) {
  fail(`入口文件不存在：src/${project}.ts`);
}

const platformPath = join(root, "public", "platform-config.json");
if (!existsSync(platformPath)) {
  fail(`缺少 ${platformPath}，请先保留默认 platform-config.json`);
}

let platformJson;
try {
  platformJson = JSON.parse(readFileSync(platformPath, "utf8"));
} catch (e) {
  fail(`无法解析 ${platformPath}: ${e.message}`);
}

platformJson.Title = title.trim();
writeFileSync(platformPath, `${JSON.stringify(platformJson, null, 2)}\n`, "utf8");

const genPath = join(root, "src", "generated-entry.ts");
const importPath = `./${project}.ts`;
const genContent = `// auto-generated by scripts/run-project.mjs — do not edit
export function loadProjectEntry() {
  return import(${JSON.stringify(importPath)});
}
`;
writeFileSync(genPath, genContent, "utf8");

const env = {
  ...process.env,
  VITE_APP_TITLE: title.trim()
};

const viteCli = join(root, "node_modules", "vite", "bin", "vite.js");
if (!existsSync(viteCli)) {
  fail("未找到 vite，请先在该目录执行 pnpm install");
}

if (mode === "build") {
  const dist = join(root, "dist");
  try {
    rmSync(dist, { recursive: true, force: true });
  } catch {
    /* ignore */
  }
}

const viteArgs = mode === "build" ? [viteCli, "build"] : [viteCli];

const result = spawnSync(process.execPath, viteArgs, {
  cwd: root,
  env,
  stdio: "inherit"
});

process.exit(result.status ?? 1);
